var mainData = [
  {
    category: "华文听写 2025",
    title: "第一课，一起看电视",
    subtitle: "第一课",
    testdate: "2025年1月21日 (星期二)",
    group: [
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "句式",
      "句式",
      "默写"
    ],
    pronunciation: [
      "liǎo jiě , yù bào",
      "qíng kuàng , bō fàng",
      "lián xù jù",
      "sān shí jí",
      "lán qiú mí",
      "huàn , fāng yán",
      "tóu lán , shǒu zhǎng",
      "pí juàn",
      "xīn wén , nèi wài",
      "dǎo , guān zhòng",
      "rù mí , gòng",
      "jīng cǎi , qiú sài",
      "rěn bù zhù",
      "fēi kuài , gāng gāng",
      "jiàn yì , wǔ dǎo",
      "mì mì",
      "liǎo jiě qíng kuàng",
      "gù shì yǒu qù",
      "qiú sài jīng cǎi",
      "shēn tǐ pí bèi",
      "zhè bù diàn yǐng hěn hǎo kàn , guān zhòng dōu kàn de rù mí le.",
      "zhè ge gù shì hěn yǒu qù , xiǎo péng yǒu men dōu tīng de rù mí le.",
      "wǒ xià le yī tiào , xīn lǐ hǎo xiàng yǒu shí wǔ gè diào tǒng dǎ shuǐ , qī shàng bā xià de"
    ],
    sentences: [
      "了解、预报",
      "情况、播放",
      "连续剧",
      "三十集",
      "篮球迷",
      "换、方言",
      "投篮、手掌",
      "疲倦",
      "新闻、内外",
      "岛、观众",
      "入迷、共",
      "精彩、球赛",
      "忍不住",
      "飞快、刚刚",
      "建议、舞蹈",
      "秘密",
      "了解情况",
      "故事有趣",
      "球赛精彩",
      "身体疲惫",
      "这部电影很好看，观众都看的入迷了。",
      "这个故事很有趣，小朋友们都听得入迷了。",
      "我吓了一跳，心里好像有十五个吊桶打水，七上八下的"
    ]
  },
  {
    category: "华文听写 2025",
    title: "第二课，我们是兄弟姐妹",
    subtitle: "第二课",
    testdate: "2025年2月4日 (星期二)",
    group: [
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "句式",
      "句式",
      "默写"
    ],
    pronunciation: [
      "nǐ yì yán",
      "wǒ yì yǔ",
      "mào zi , wài tào",
      "yān huā tào",
      "jǐn jiē zhe",
      "qīng pén dà yǔ",
      "hū hū dì",
      "gǎn jǐn , chēng sǎn",
      "shí fēn",
      "píng guǒ , cí yǔ",
      "yú wán , dǎ gǔ",
      "gū gu",
      "wū yún mì bù",
      "kào dé jǐn jǐn de",
      "nuǎn nuǎn de , biǎo shì",
      "hū rán",
      "líng jī yí dòng",
      "jǐ zài yì qǐ",
      "dān xīn , bú pà",
      "biǎo shì tóng yì",
      "jué de dān xīn",
      "kào dé jǐn jǐn de",
      "yí chuàn yú wán",
      "yí gè xiǎo gǔ",
      "gǎn jǐn huí jiā",
      "wǒ lěng dé zhí fā dǒu",
      "wǒ hé jiě jie xiào dé shí fēn kāi xīn",
      "zhè jiàn shì ràng wǒ míng bái le yǐ hòu bù guǎn zuò shén me shì qíng dōu yào xiǎo xīn ， cái néng bì miǎn fā shēng yì wài 。"
    ],
    sentences: [
      "你一言",
      "我一语",
      "帽子、外套",
      "烟花套",
      "紧接着",
      "倾盆大雨",
      "呼呼地",
      "赶紧、撑伞",
      "十分",
      "苹果、词语",
      "鱼丸、打鼓",
      "姑姑",
      "乌云密布",
      "靠得紧紧的",
      "暖暖的、表示",
      "忽然",
      "灵机一动",
      "挤在一起",
      "担心、不怕",
      "表示同意",
      "觉得担心",
      "靠得紧紧的",
      "一串鱼丸",
      "一个小鼓",
      "赶紧回家",
      "我冷得直发抖",
      "我和姐姐笑得十分开心",
      "这件事让我明白了以后不管做什么事情都要小心，才能避免发生意外。"
    ]
  },
  {
    category: "华文听写 2025",
    title: "第二课，我们是兄弟姐妹",
    subtitle: "第二课",
    testdate: "2025年2月6日 (星期四)",
    group: ["", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    pronunciation: [
      "pà",
      "tǎo lùn",
      "gū gu",
      "hū rán",
      "yí chuàn yú wán",
      "líng jī yí dòng",
      "jí jí máng máng",
      "wǒ hé jiě jie xiào dé shí fēn kāi xīn",
      "fēng hū hū dì chuī zhe ， wǒ lěng dé zhí fā dǒu 。",
      "tiān kōng wū yún mì bù ， jǐn jiē zhe xià qǐ le qīng pén dà yǔ 。",
      "“ líng ！ ” fàng xué de líng shēng xiǎng le ， tóng xué men yì wō fēng dì chōng chū kè shì ， xiàng xiào mén pǎo qù 。",
      "qì hū hū de ， shuō bù chū huà lái",
      "qì dé mǎn liǎn tōng hóng",
      "qì dé huǒ mào sān zhàng ， liǎn yí zhèn hóng yí zhèn bái ， quán shēn fā dǒu"
    ],
    sentences: [
      "怕",
      "讨论",
      "姑姑",
      "忽然",
      "一串鱼丸",
      "灵机一动",
      "急急忙忙",
      "我和姐姐笑得十分开心",
      "风呼呼地吹着，我冷得直发抖。",
      "天空乌云密布，紧接着下起了倾盆大雨。",
      "“铃！”放学的铃声响了，同学们一窝蜂地冲出课室，向校门跑去。",
      "气呼呼的，说不出话来",
      "气得满脸通红",
      "气得火冒三丈，脸一阵红一阵白，全身发抖"
    ]
  }
];
