var mainData = [
  {
    category: "华文听写 2025",
    title: "第一课，一起看电视",
    subtitle: "第一课",
    testdate: "2025年1月21日 (星期二)",
    group: [
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "句式",
      "句式",
      "默写"
    ],
    pronunciation: [
      "liǎo jiě , yù bào",
      "qíng kuàng , bō fàng",
      "lián xù jù",
      "sān shí jí",
      "lán qiú mí",
      "huàn , fāng yán",
      "tóu lán , shǒu zhǎng",
      "pí juàn",
      "xīn wén , nèi wài",
      "dǎo , guān zhòng",
      "rù mí , gòng",
      "jīng cǎi , qiú sài",
      "rěn bù zhù",
      "fēi kuài , gāng gāng",
      "jiàn yì , wǔ dǎo",
      "mì mì",
      "liǎo jiě qíng kuàng",
      "gù shì yǒu qù",
      "qiú sài jīng cǎi",
      "shēn tǐ pí bèi",
      "zhè bù diàn yǐng hěn hǎo kàn , guān zhòng dōu kàn de rù mí le.",
      "zhè ge gù shì hěn yǒu qù , xiǎo péng yǒu men dōu tīng de rù mí le.",
      "wǒ xià le yī tiào , xīn lǐ hǎo xiàng yǒu shí wǔ gè diào tǒng dǎ shuǐ , qī shàng bā xià de"
    ],
    sentences: [
      "了解、预报",
      "情况、播放",
      "连续剧",
      "三十集",
      "篮球迷",
      "换、方言",
      "投篮、手掌",
      "疲倦",
      "新闻、内外",
      "岛、观众",
      "入迷、共",
      "精彩、球赛",
      "忍不住",
      "飞快、刚刚",
      "建议、舞蹈",
      "秘密",
      "了解情况",
      "故事有趣",
      "球赛精彩",
      "身体疲惫",
      "这部电影很好看，观众都看的入迷了。",
      "这个故事很有趣，小朋友们都听得入迷了。",
      "我吓了一跳，心里好像有十五个吊桶打水，七上八下的"
    ]
  },
  {
    category: "华文听写 2025",
    title: "第二课，我们是兄弟姐妹 (H)",
    subtitle: "第二课",
    testdate: "2025年2月4日 (星期二)",
    group: [
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "句式",
      "句式",
      "默写"
    ],
    pronunciation: [
      "nǐ yì yán",
      "wǒ yì yǔ",
      "mào zi , wài tào",
      "yān huā bàng",
      "jǐn jiē zhe",
      "qīng pén dà yǔ",
      "hū hū dì",
      "gǎn jǐn , chēng sǎn",
      "shí fēn",
      "píng guǒ , cí yǔ",
      "yú wán , dǎ gǔ",
      "gū gu",
      "wū yún mì bù",
      "kào dé jǐn jǐn de",
      "nuǎn nuǎn de , biǎo shì",
      "hū rán",
      "líng jī yí dòng",
      "jǐ zài yì qǐ",
      "dān xīn , bú pà",
      "biǎo shì tóng yì",
      "jué de dān xīn",
      "kào dé jǐn jǐn de",
      "yí chuàn yú wán",
      "yí gè xiǎo gǔ",
      "gǎn jǐn huí jiā",
      "wǒ lěng dé zhí fā dǒu",
      "wǒ hé jiě jie xiào dé shí fēn kāi xīn",
      "zhè jiàn shì ràng wǒ míng bái le yǐ hòu bù guǎn zuò shén me shì qíng dōu yào xiǎo xīn ， cái néng bì miǎn fā shēng yì wài 。"
    ],
    sentences: [
      "你一言",
      "我一语",
      "帽子、外套",
      "烟花棒",
      "紧接着",
      "倾盆大雨",
      "呼呼地",
      "赶紧、撑伞",
      "十分",
      "苹果、词语",
      "鱼丸、打鼓",
      "姑姑",
      "乌云密布",
      "靠得紧紧的",
      "暖暖的、表示",
      "忽然",
      "灵机一动",
      "挤在一起",
      "担心、不怕",
      "表示同意",
      "觉得担心",
      "靠得紧紧的",
      "一串鱼丸",
      "一个小鼓",
      "赶紧回家",
      "我冷得直发抖",
      "我和姐姐笑得十分开心",
      "这件事让我明白了以后不管做什么事情都要小心，才能避免发生意外。"
    ]
  },
  {
    category: "华文听写 2025",
    title: "第三课，妈妈，对不起 (H)",
    subtitle: "第三课",
    testdate: "2025年2月18日(星期二)",
    group: [
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识读词语",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "识写字词",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "词语搭配",
      "句式",
      "句式",
      "句式",
      "默写"
    ],
    pronunciation: [
      "mó xíng , zuì jìn",
      "fàng shǒu , jiào xǐng",
      "shòu bù liǎo",
      "lǎo pó po , tūn",
      "shuō le yí gè huǎng",
      "gǎn dòng , luò xià",
      "guān xīn , zhěng tiān",
      "pī píng , gǎn xiè",
      "zūn jìng , zhǎng bèi",
      "jǐng chá , hòu huǐ",
      "fā pí qi",
      "yì wǎn , yún tūn miàn",
      "mí shàng , bàn yè",
      "shè bù dé",
      "zhēng kāi , bǔ xí",
      "jiē shàng , zhǔ",
      "yǎn lèi",
      "zūn jìng zhǎng bèi",
      "zhēng kāi yǎn jīng",
      "yì zhí láo dao",
      "yǎn lèi luò xià",
      "zhěng tiān pī píng",
      "mā ma shuō ： “ hái zi ， yǐ jīng bù zǎo le ， gǎn kuài shàng chuáng shuì jiào ba ！ ”",
      "“ hái zi ， ” mā ma shuō ， “ yǐ jīng bù zǎo le ， gǎn kuài shàng chuáng shuì jiào ba ！ ”",
      "“ hái zi ， yǐ jīng bù zǎo le ， gǎn kuài shàng chuáng shuì jiào ba ！ ” mā ma shuō 。",
      "xiǎo huá kàn jiàn shū pò le ， qì dé mǎn liǎn tōng hóng ， qì chōng chōng dì pǎo qù gào sù lǎo shī 。"
    ],
    sentences: [
      "模型、最近",
      "放手、叫醒",
      "受不了",
      "老婆婆、吞",
      "说了一个谎",
      "感动、落下",
      "关心、整天",
      "批评、感谢",
      "尊敬、长辈",
      "警察、后悔",
      "发脾气",
      "一碗、云吞面",
      "迷上、半夜",
      "舍不得",
      "睁开、补习",
      "街上、煮",
      "眼泪",
      "尊敬长辈",
      "睁开眼睛",
      "一直唠叨",
      "眼泪落下",
      "整天批评",
      "妈妈说：“孩子，已经不早了，赶快上床睡觉吧！”",
      "“孩子，”妈妈说，“已经不早了，赶快上床睡觉吧！”",
      "“孩子，已经不早了，赶快上床睡觉吧！”妈妈说。",
      "小华看见书破了，气得满脸通红，气冲冲地跑去告诉老师。"
    ]
  },
  {
    category: "华文听写 2025",
    title: "第三课，妈妈，对不起 (D)",
    subtitle: "第三课",
    testdate: "2025年2月20日 (星期四)",
    group: ["", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    pronunciation: [
      "nín",
      "tōu dōng xī",
      "hòu huǐ",
      "chǎo jià",
      "zuì jìn",
      "bǔ xí",
      "kàn dé rù mí",
      "zūn jìng zhǎng bèi",
      "tā fēi cháng gǎn dòng ， yǎn lèi rěn bú zhù luò le xià lái 。",
      "zuó wǎn ， wǒ yì zhí wán yóu xì ， shè bù dé fàng shǒu 。",
      "kàn dào zhè yí mù ， tā jí dé xiàng rè guō shàng de mǎ yǐ — — tuán tuán zhuàn 。",
      "xīn lǐ hěn nán guò ， lèi shuǐ jiù cóng yǎn lǐ liú le xià lái",
      "shāng xīn dé fàng shēng dà kū ， lèi liú mǎn miàn",
      "yǎn lèi xiàng duàn le xiàn de zhēn zhū yí yàng liú xià lái"
    ],
    sentences: [
      "您",
      "偷东西",
      "后悔",
      "吵架",
      "最近",
      "补习",
      "看得入迷",
      "尊敬长辈",
      "他非常感动，眼泪忍不住落了下来。",
      "昨晚，我一直玩游戏，舍不得放手。",
      "看到这一幕，他急得像热锅上的蚂蚁——团团转。",
      "心里很难过，泪水就从眼里流了下来",
      "伤心得放声大哭，泪流满面",
      "眼泪像断了线的珍珠一样流下来"
    ]
  },
  {
    category: "华文听写 2025",
    title: "第四课，今天我值日 (D)",
    subtitle: "第四课",
    testdate: "2025年3月6日 (星期四)",
    group: ["", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    pronunciation: [
      "fù zé",
      "shí táng",
      "chā duì",
      "zhù yì",
      "zé rèn",
      "ān jìng",
      "gān jìng",
      "zhè ge zì hěn nán ， wǒ men shuí yě bú huì rèn 。",
      "zhè dào tí hěn nán ， tóng xué men shuí dōu bú huì zuò 。",
      "yóu yú tā shēng bìng le ， jīn tiān méi lái xué xiào 。",
      "tā xià dé liǎng tuǐ fā ruǎn ， mào chū lěng hàn ， yì shí bù zhī rú hé shì hǎo 。",
      "xià dé liǎn qīng chún bái ， quán shēn fā dǒu ， zhí mào lěng hàn",
      "fēi cháng jīng yà ， mù dèng kǒu dāi",
      "zhī dào cuò le ， xīn lǐ jué de hěn cán kuì ， hóng zhe liǎn ， dī zhe tóu ， bù gǎn shuō huà"
    ],
    sentences: [
      "负责",
      "食堂",
      "插队",
      "注意",
      "责任",
      "安静",
      "干净",
      "这个字很难，我们谁也不会认。",
      "这道题很难，同学们谁都不会做。",
      "由于她生病了，今天没来学校。",
      "他吓得两腿发软，冒出冷汗，一时不知如何是好。",
      "吓得脸青唇白，全身发抖，直冒冷汗",
      "非常惊讶，目瞪口呆",
      "知道错了，心里觉得很惭愧，红着脸，低着头，不敢说话"
    ]
  },
  {
    category: "华文听写 2025",
    title: "第五课，我不怕打针 (D)",
    subtitle: "第五课",
    testdate: "2025年3月20日 (星期四)",
    group: ["", "", "", "", "", "", "", "", "", "", "", "", "", ""],
    pronunciation: [
      "fù zé",
      "shí táng",
      "chā duì",
      "zhù yì",
      "zé rèn",
      "ān jìng",
      "gān jìng",
      "zhè ge zì hěn nán ， wǒ men shuí yě bú huì rèn 。",
      "zhè dào tí hěn nán ， tóng xué men shuí dōu bú huì zuò 。",
      "yóu yú tā shēng bìng le ， jīn tiān méi lái xué xiào 。",
      "tā xià dé liǎng tuǐ fā ruǎn ， mào chū lěng hàn ， yì shí bù zhī rú hé shì hǎo 。",
      "xià dé liǎn qīng chún bái ， quán shēn fā dǒu ， zhí mào lěng hàn",
      "fēi cháng jīng yà ， mù dèng kǒu dāi",
      "zhī dào cuò le ， xīn lǐ jué de hěn cán kuì ， hóng zhe liǎn ， dī zhe tóu ， bù gǎn shuō huà"
    ],
    sentences: [
      "吃药",
      "闭上眼睛",
      "课室",
      "打针",
      "结束",
      "伸出手臂",
      "检查身体",
      "我们的作业有四个项目。",
      "小齐的视力变差了，他闷闷不乐。",
      "小安一看到针，就“哇”的一声大哭起来。",
      "她红着脸，低下头，难为情地说：“对不起！”。",
      "急得像热锅上的蚂蚁，不知道怎么做",
      "吓得不管三七二十一，拔腿就跑"
    ]
  }
];
