var mainData = [
    {
        "title": "Unit 1 - Fearless Phil",
        "subtitle":"Unit 1",
        "testdate":"18/01/2024",
        "words": [
            "shiver",
            "rumbled",
            "grumbled",
            "snarling",
            "stumbled",
            "quivered",
            "trembled",
            "bolted",
            "perched",
            "towering",
            "invincible",
            "fearless",
            "cunning",
            "threatening",
            "encouragement",
            "stomach",
            "jacket",
            "swooped down",
            "menacing growl",
            "mountain track"
        ],
        "meanings": [
            "to shake slightly because one feels cold, ill, or frightened",
            "a continuous low sound",
            "to complain about someone or something in an annoyed way",
            "to make a deep, rough sound while showing the teeth, usually in anger or to speak",
            "to hit your foot against something while walking and almost fall",
            "to shake slightly",
            "to shake slightly in a way that you cannot control, for example because you are frightened, angry, or excited",
            "to move very fast, especially as a result of being frightened",
            "to rest on a branch or other object, to sit or be on the edge or top of something",
            "very high or very tall",
            "impossible to defeat",
            "brave, not afraid of anything",
            "being clever something to get what you want, especially by tricking other people",
            "expressing the possibility that something unwanted or unpleasant will happen",
            "words or behaviour that give someone confidence to do something",
            "an organ in the body where food is digested",
            "a short coat",
            "to move very quickly and easily through the air, down from a high position in order to attack",
            "a low, rough sound, usually in anger",
            "a path that is narrower than a road, often with an uneven surface"            
        ],
        "sentences": [
            "The weird sounds made us <b><u>shiver</u></b> with fear as we walked.",
            "His stomach <b><u>rumbled</u></b> loudly as he had not taken his breakfast.",
            "Marvin <b><u>grumbled</u></b> that he had a lot of homework to do during the holidays.",
            "The dog was baring its teeth and <b><u>snarling</u></b> at another dog that stole its food.",
            "The hunter fell down when his feet <b><u>stumbled</u></b> on a log.",
            "She <b><u>quivered</u></b> at the thought of being left alone in the jungle.",
            "The little girl <b><u>trembled</u></b> with fear when she heard a strange knock on her door.",
            "He <b><u>bolted</u></b> down the stairs when he heard the doorbell ring.",
            "The bird flew and <b><u>perched</u></b> on a branch high up on a tree.",
            "James is so tall that he is <b><u>towering</u></b> over his peers in class.",
            "He was an <b><u>invincible</u></b> warrior whom no one could defeat.",
            "Wu Song was a <b><u>fearless</u></b> man who fought and killed a tiger with his bare hands.",
            "Henry is <b><u>cunning</u></b> and knows what to say or do to get his way.",
            "The clouds look <b><u>threatening</u></b>, signalling that a thunderstorm is coming soon.",
            "Mary's parents gave her some words of <b><u>encouragement</u></b> before she went for her examination.",
            "Tommy must be hungry because his <b><u>stomach</u></b> has started growling.",
            "As the weather was very cold, Simon put on a <b><u>jacket</u></b> before going out.",
            "Alan shrieked when the flying insect <b><u>swooped down</u></b> in front of him",
            "The dog gave a <b><u>menacing growl</u></b> as the thief tried to enter the house.",
            "Many travellers used the <b><u>mountain track</u></b> to get to the top of the mountain."
        ],
    },
    {
        "category": "English Spelling 2024",
        "title": "Unit 2 - The Gruffalo",
        "subtitle":"Unit 2",
        "testdate":"Test Date 08/02/2024",
        "words": [
            "ambled",
            "rescued",
            "terrible",
            "ecstatic",
            "dejected",
            "wonderful",
            "astounding",
            "poisonous",
            "roasted",
            "responsible",
            "witty",
            "feast",
            "occasion",
            "tusks",
            "prickles",
            "treetop",
            "underground",
            "burst out laughing",
            "knobbly knees",
            "scariest creature"
        ],
        "meanings": [
            "to walk in a slow and relaxed way",
            "to save someone or something from a dangerous, harmful, or difficult situation",
            "very unpleasant or serious or bad",
            "very happy",
            "unhappy, disappointed, or without hope",
            "extremely good",
            "so surprising that it is almost impossible to believe",
            "very harmful and able to cause illness or death",
            "cooked in an oven or over a fire",
            "having good judgment and the ability to act correctly and make decisions on your own",
            "using words in a clever and funny way",
            "a special meal with very good food or a large meal for many people",
            "a special or formal event",
            "two, long, curved teeth that stick out from the mouth of some animals, especially elephants and walruses",
            "thin, sharp points that stick out of a plant or animal",
            "the highest part of a tree",
            "below the surface of the earth; below ground",
            "to make the sounds and movements of the face and body that express happiness or amusement",
            "having lumps on the surface of the middle joint of the leg that allows the leg to bend",
            "the most frightening living thing"      
        ],
        "meanings_cn": [
            "漫步;缓行;慢跑",
            "抢救;营救;援救",
            "可怕的，骇人的;<口>糟糕的，很蹩脚的;极度的;困难的，艰难的;",
            "欣喜若狂",
            "沮丧的;垂头丧气的;情绪低落的",
            "精彩的;绝妙的;令人惊奇的;令人赞叹的;令人高兴的;使人愉快的",
            "令人震惊的;使大吃一惊的",
            "有毒的;引起中毒的;恶毒的;邪恶的;分泌毒素的;极端讨厌(或不友善)的;能毒伤人的",
            "烘，烤，焙(肉等);烘烤，焙，炒(坚果、豆子等);(对某人)非常生气，严厉批评",
            "负责任的, 负责的",
            "言辞诙谐的;巧妙的;妙趣横生的;机智的",
            "盛宴;宴会;(宗教的)节日，节期;",
            "场合;…的时候;时机;理由;适当的机会;某次;特别的事情(或仪式、庆典)",
            "獠牙;(象和某些其他动物的)长牙",
            "(植物的)芒刺;荆棘;(动物的)皮刺，刺毛;",
            "树梢, 树顶",
            "地下的;秘密的，非法的，暗中的，地下的(尤指反政府的);地面以下的",
            "大笑起来;放声大笑;突然大笑起来;",
            "骨节突出的膝盖",
            "最吓人的生物"              
        ],
        "pronunciation":[
            "/ˈæmbl/",
            "/ˈreskjuːd/",
            "/ˈterəbl/",
            "/ɪkˈstætɪk/",
            "/dɪˈdʒektɪd/",
            "/ˈwʌndəfl/",
            "/əˈstaʊndɪŋ/",
            "/ˈpɔɪzənəs/",
            "/ˈrəʊstɪd/",
            "/rɪˈspɒnsəbl/",
            "/ˈwɪti/",
            "/fiːst/",
            "/əˈkeɪʒn/",
            "/tʌsks/",
            "/ˈprɪklz/",
            "/ˈtriːtɒp/",
            "/ˌʌndəˈɡraʊnd/",
            "/bɜːst aʊt ˈlɑːfɪŋ/",
            "/ˈnɒbli niːz/",
            "/ˈskeərɪɪst ˈkriːtʃə(r)/"
        ],
        "sentences": [
            "Paul ambled along the beach, enjoying the cool evening breeze.",
            "The firefighters braved the burning building and rescued the trapped victims.",
            "After a busy day at work, Mrs Ng had a terrible headache.",
            "Lucy was ecstatic when her mother gave her permission to keep a pet dog.",
            "Dan looked dejected when his teacher did not select him to be the monitor.",
            "As we had a wonderful time in Japan last year, we plan to go there again.",
            "The concert that was presented by the Primary 6 students was an astounding success.",
            "The cobra is a poisonous snake. Its venom can kill people.",
            "Jane enjoyed the roasted turkey that Aunt May had prepared for Christmas dinner.",
            "Peter is a responsible class monitor who carries out his duties well.",
            "Their form teacher is very witty and the students are amused by his smart remarks.",
            "Mother had prepared a feast of dishes for the family reunion dinner.",
            "Sarah is going to dress up for the occasion as it is her best friend's wedding.",
            "An elephant has two tusks with a long nose in between them.",
            "The tiny prickles on the cactus plant are actually its leaves.",
            "We spent a night in a treetop house amid the birds and the butterflies.",
            "An earthworm burrows underground in the soil and loosens it so that plants can grow better.",
            "The jolly king burst out laughing when the little puppy licked his face.",
            "Old Uncle Tong has knobbly knees because he has had many surgeries on his legs.",
            "The young child believes that the dinosaur is the scariest creature on earth."    
        ]
    },
    {
        "category": "English Spelling 2024",
        "title": "Unit 3 - Camille And The Sunflowers",
        "subtitle":"Unit 3",
        "testdate":"Test Date 23/02/2024",
        "words": [
            "teased",
            "hurled",
            "beamed",
            "sprinted",
            "withered",
            "billowing",
            "strange",
            "delicious",
            "confusion",
            "techniques",
            "opportunity",
            "furniture",
            "canvas",
            "exhibits",
            "paintings",
            "photograph",
            "galleries",
            "museums",
            "grown-ups",
            "slipped out"
        ],
        "meanings": [
            "to laugh at someone or say unkind things about them, either because you are joking or because you want to upset that person",
            "to throw something with a lot of force, usually in an angry or violent way",
            "to smile with obvious pleasure",
            "to run as fast as you can over a short distance",
            "dry and decaying",
            "moving mass of something, such as smoke or cloud, spreading over a large area",
            "not known or familiar",
            "having a very pleasant taste or smell",
            "a situation, often with a lot of activity and noise, in which people do not know what to do",
            "ways of doing an activity that needs skill",
            "chance to do something",
            "things such as chairs, tables and beds that are used in a home or office",
            "a piece of strong, coarse cloth used by artists for painting on, usually with oil paints",
            "objects that are shown to the public in places such as museums",
            "a picture created by putting paint on a surface",
            "a picture produced using camera",
            "rooms or buildings that are used for showing works of art",
            "buildings where people can go to view works of art or objects of interest to science or history",
            "an adult, used especially when talking to children",
            "to leave quietly or quickly so that no one will notice"    
        ],
        "meanings_cn": [
            "取笑",
            "抛掷",
            "发光",
            "冲刺",
            "凋零",
            "翻滚",
            "奇怪的",
            "美味的",
            "混乱",
            "技术",
            "机会",
            "家具",
            "画布",
            "展品",
            "画作",
            "照片",
            "画廊",
            "博物馆",
            "成年人",
            "溜走"           
        ],
        "pronunciation":[
            "/tiːzd/",
            "/hɜːrld/",
            "/biːmd/",
            "/ˈsprɪntɪd/",
            "/ˈwɪðərd/",
            "/ˈbɪloʊɪŋ/",
            "/streɪndʒ/",
            "/dɪˈlɪʃəs/",
            "/kənˈfjuːʒən/",
            "/tɛkˈniːks/",
            "/ˌɑpərˈtunəti/",
            "/ˈfɜːrnɪtʃər/",
            "/ˈkænvəs/",
            "/ɪɡˈzɪbɪts/",
            "/ˈpeɪntɪŋz/",
            "/ˈfoʊtəɡræf/",
            "/ˈɡæləriz/",
            "/mjuˈziːəmz/",
            "/ɡroʊn ʌps/",
            "/slɪpt aʊt/"
        ],
        "sentences": [
            "Bobby teased his sister to irritate her.",
            "He was so angry that he hurled the book at his brother.",
            "Mary beamed at the principal as she received the prize.",
            "The boy sprinted to the bus stop to catch the bus that was about to leave.",
            "The flowers withered as they were not watered for a few days.",
            "There was smoke billowing out of the burning building.",
            "With so many strange faces around her, the baby started to cry.",
            "The cake that my mother baked for my birthday is delicious.",
            "In the midst of the confusion after the fire, Ali got separated from his parents.",
            "Sam went for a course to learn some techniques in making clay objects by hand.",
            "She was grateful for having been given the opportunity to perform on stage in front of a large audience.",
            "Mr Tan decided to change the furniture in his house for Chinese New Year.",
            "Many people gathered around the well-known painter when he started painting on a canvas.",
            "The museum has a fascinating collection of exhibits ranging from pottery to clothings.",
            "Vincent Van Gogh's paintings have captured the minds and hearts of millions of art lovers.",
            "Rhonda likes to have her photograph taken with her friends.",
            "The art galleries are always fully packed with students viewing the paintings.",
            "He is a well-travelled man who has been to many museums around the world.",
            "This book is suitable for grown-ups but not children to read.",
            "Camille slipped out through the back door and ran down the street."   
        ]
    },
    {
        "category": "English Spelling 2024",
        "title": "Unit 4 - Predators And Prey",
        "subtitle":"Unit 4",
        "testdate":"Test Date 28/03/2024",
        "words": [
        "forage",
        "survive",
        "escape",
        "camouflage",
        "stalk",
        "grunt",
        "resemble",
        "illegal",
        "endangered",
        "tactics",
        "trait",
        "threat",
        "predators",
        "otters",
        "quills",
        "talons",
        "fangs",
        "habitat",
        "shelter",
        "fishermen"
        ],
        "meanings": [
        "to search widely for food",
        "to continue to live or exist",
        "to get away from a place where you were not allowed to leave",
        "(of an animal or plant) to have a colour or shape that makes it appear to mix with its natural environment so that it cannot be seen or attacked",
        "to move slowly and quietly towards an animal or a person, in order to kill, catch or harm it or them",
        "(of a person) to make a short, low sound instead of speaking, usually because of anger or pain",
        "to look like another person or thing",
        "not allowed by law",
        "animals or plants that may soon not exist because there are very few now alive.",
        "methods you use to achieve something",
        "a particular characteristic that can produce a particular type of behaviour",
        "a person or thing likely to cause damage or danger.",
        "animals that kill and eat other animals",
        "mammals with four legs and short brown fur that swim well and eat fish",
        "any of the long sharp pointed hairs on the body of a porcupine",
        "sharp nails on the feet of a bird that it uses when hunting animals",
        "long, sharp teeth that animals such as snakes and dogs have",
        "the natural environment in which an animal or plant usually lives",
        "a place to give protection from bad weather, danger, or attack",
        "people who catch fish for a living"
        ],
        "meanings_cn": [
        "觅食",
        "幸存",
        "逃脱",
        "伪装",
        "潜行",
        "咕噜声",
        "类似",
        "非法的",
        "濒危的",
        "战术",
        "特征",
        "威胁",
        "捕食者",
        "水獭",
        "刺",
        "爪",
        "獠牙",
        "栖息地",
        "庇护所",
        "渔民"           
        ],
        "pronunciation":[
        "/fɔːrɪdʒ/",
        "/səˈvaɪv/",
        "/ɪˈskeɪp/",
        "/ˈkæməflɑːʒ/",
        "/stɔːk/",
        "/ɡrʌnt/",
        "/rɪˈzembl/",
        "/ˈɪlɪɡəl/",
        "/ɪnˈdeɪndʒəd/",
        "/ˈtæktɪks/",
        "/treɪt/",
        "/θret/",
        "/ˈprɛdətərz/",
        "/ˈɒtərz/",
        "/kwɪlz/",
        "/ˈtælənz/",
        "/fæŋz/",
        "/ˈhæbɪtæt/",
        "/ˈʃɛltər/",
        "/ˈfɪʃəmən/"
        ],
        "sentences": [
        "The animals forage for food in the woods.",
        "Living things need air, food, and water to survive.",
        "The mouse struggled to escape the trap that it was caught in.",
        "The hare's white fur helps it camouflage with its snowy surroundings.",
        "Lions stalk their prey as a team before launching an attack.",
        "The boys grunt loudly when they are working as they are tired and hungry.",
        "The tiger has stripes that resemble shadows of the forest.",
        "Some animals may soon become extinct due to man's illegal hunting.",
        "The wild tiger is considered critically endangered.",
        "Jason tried to think of different tactics to beat his sister at a game of chess.",
        "Kindness is her best trait, making her well-liked by her peers.",
        "Large pythons are a threat to orangutans.",
        "Predators are animals that hunt and kill other animals for food.",
        "Henry spotted a family of otters swimming along the river.",
        "The quills on a porcupine may drop off when it shakes its body.",
        "The eagle dug its sharp talons into its prey and then flew up to the sky.",
        "The snake sank its fangs into its victim.",
        "Due to deforestation, many animals are losing their natural habitat.",
        "As soon as they heard thunder, the group of scouts quickly looked for shelter.",
        "The fishermen mend the holes in their nets to ensure that they get the most catch when they go out to sea."
        ]
    }
]