var mainData = [
    {
        "title": "Unit 1 - Fearless Phil",
        "subtitle":"Unit 1",
        "testdate":"18/01/2024",
        "words": [
            "shiver",
            "rumbled",
            "grumbled",
            "snarling",
            "stumbled",
            "quivered",
            "trembled",
            "bolted",
            "perched",
            "towering",
            "invincible",
            "fearless",
            "cunning",
            "threatening",
            "encouragement",
            "stomach",
            "jacket",
            "swooped down",
            "menacing growl",
            "mountain track"
        ],
        "meanings": [
            "to shake slightly because one feels cold, ill, or frightened",
            "a continuous low sound",
            "to complain about someone or something in an annoyed way",
            "to make a deep, rough sound while showing the teeth, usually in anger or to speak",
            "to hit your foot against something while walking and almost fall",
            "to shake slightly",
            "to shake slightly in a way that you cannot control, for example because you are frightened, angry, or excited",
            "to move very fast, especially as a result of being frightened",
            "to rest on a branch or other object, to sit or be on the edge or top of something",
            "very high or very tall",
            "impossible to defeat",
            "brave, not afraid of anything",
            "being clever something to get what you want, especially by tricking other people",
            "expressing the possibility that something unwanted or unpleasant will happen",
            "words or behaviour that give someone confidence to do something",
            "an organ in the body where food is digested",
            "a short coat",
            "to move very quickly and easily through the air, down from a high position in order to attack",
            "a low, rough sound, usually in anger",
            "a path that is narrower than a road, often with an uneven surface"            
        ],
        "sentences": [
            "The weird sounds made us <b><u>shiver</u></b> with fear as we walked.",
            "His stomach <b><u>rumbled</u></b> loudly as he had not taken his breakfast.",
            "Marvin <b><u>grumbled</u></b> that he had a lot of homework to do during the holidays.",
            "The dog was baring its teeth and <b><u>snarling</u></b> at another dog that stole its food.",
            "The hunter fell down when his feet <b><u>stumbled</u></b> on a log.",
            "She <b><u>quivered</u></b> at the thought of being left alone in the jungle.",
            "The little girl <b><u>trembled</u></b> with fear when she heard a strange knock on her door.",
            "He <b><u>bolted</u></b> down the stairs when he heard the doorbell ring.",
            "The bird flew and <b><u>perched</u></b> on a branch high up on a tree.",
            "James is so tall that he is <b><u>towering</u></b> over his peers in class.",
            "He was an <b><u>invincible</u></b> warrior whom no one could defeat.",
            "Wu Song was a <b><u>fearless</u></b> man who fought and killed a tiger with his bare hands.",
            "Henry is <b><u>cunning</u></b> and knows what to say or do to get his way.",
            "The clouds look <b><u>threatening</u></b>, signalling that a thunderstorm is coming soon.",
            "Mary's parents gave her some words of <b><u>encouragement</u></b> before she went for her examination.",
            "Tommy must be hungry because his <b><u>stomach</u></b> has started growling.",
            "As the weather was very cold, Simon put on a <b><u>jacket</u></b> before going out.",
            "Alan shrieked when the flying insect <b><u>swooped down</u></b> in front of him",
            "The dog gave a <b><u>menacing growl</u></b> as the thief tried to enter the house.",
            "Many travellers used the <b><u>mountain track</u></b> to get to the top of the mountain."
        ],
    }
]