var mainData = [
    {
        "title": "Unit 1 - Chicken Rice",
        "subtitle":"Unit 1",
        "testdate":"26/01/2024",
        "words": [
            "dish",
            "lunch",
            "stall",
            "buzz",
            "hope",
            "snake",
            "crispy",
            "spicy",
            "delicious",
            "tasteless",
            "fresh",
            "disgusting",
            "ingredients",
            "curry puff",
            "chicken rice"],
        "sentences": [
            "My favourite <b><u>dish</u></b> is mee goreeng.",
            "I had nasi lemak for <b><u>lunch</u></b> yesterday afternoon.",
            "The <b><u>stall</u></b> that sells satay and ketupat is very crowded now.",
            "Sally was woken up by the <b><u>buzz</u></b> of a mosquito in her ear.",
            "We <b><u>hope</u></b> and pray that the operation will be a success.",
            "A <b><u>snake</u></b> slithered across our path.",
            "The fried chicken wings are <b><u>crispy</u></b> and tasty.",
            "The chilli is so <b><u>spicy</u></b> that I have to drink two big glasses water.",
            "The customers were very pleased with the <b><u>delicious</u></b> meal.",
            "The meat was dry and <b><u>tasteless</u></b>.",
            "Mother threw away the bread because it was not <b><u>fresh</u></b>.",
            "The food was so <b><u>disgusting</u></b> that none of us wanted to eat it.",
            "He created a fantastic meal from very few <b><u>ingredients</u></b>.",
            "I have eaten only one <b><u>curry puff</u></b> and I am already full.",
            "Mr Low tasted the <b><u>chicken rice</u></b> that he cooked and said that it was nice."],
    }
]