var mainData = [
    {
        "title": "Unit 1 - Chicken Rice",
        "subtitle":"Unit 1",
        "testdate":"26/01/2023",
        "words": [
            "dish",
            "lunch",
            "stall",
            "buzz",
            "hope",
            "snake",
            "crispy",
            "spicy",
            "delicious",
            "tasteless",
            "fresh",
            "disgusting",
            "ingredients",
            "curry puff",
            "chicken rice"],
        "sentences": [
            "My favourite <b><u>dish</u></b> is mee goreeng.",
            "I had nasi lemak for <b><u>lunch</u></b> yesterday afternoon.",
            "The <b><u>stall</u></b> that sells satay and ketupat is very crowded now.",
            "Sally was woken up by the <b><u>buzz</u></b> of a mosquito in her ear.",
            "We <b><u>hope</u></b> and pray that the operation will be a success.",
            "A <b><u>snake</u></b> slithered across our path.",
            "The fried chicken wings are <b><u>crispy</u></b> and tasty.",
            "The chilli is so <b><u>spicy</u></b> that I have to drink two big glasses water.",
            "The customers were very pleased with the <b><u>delicious</u></b> meal.",
            "The meat was dry and <b><u>tasteless</u></b>.",
            "Mother threw away the bread because it was not <b><u>fresh</u></b>.",
            "The food was so <b><u>disgusting</u></b> that none of us wanted to eat it.",
            "He created a fantastic meal from very few <b><u>ingredients</u></b>.",
            "I have eaten only one <b><u>curry puff</u></b> and I am already full.",
            "Mr Low tasted the <b><u>chicken rice</u></b> that he cooked and said that it was nice."],
    },
    {
        "title": "Unit 2 - Bad Dreams",
        "subtitle":"Unit 2",
        "testdate":"09/02/2023",
        "words": [
            "afraid",
            "sailed",
            "waited",
            "drain",
            "kitchen",
            "squirmed",
            "squeezed",
            "begged",
            "replied",
            "protected",
            "chose",
            "crowded",
            "confortable",
            "fear",
            "full"],
        "sentences": [
            "The boys were <b><u>afraid</u></b> of the dark.",
            "The boat <b><u>sailed</u></b> down the coast.",
            "I <b><u>waited</u></b> patiently for my turn to ride the horse.",
            "There was an unpleasant smell coming from the <b><u>drain</u></b>.",
            "Mother is busy cooking in the <b><u>kitchen</u></b>.",
            "The earthworm <b><u>squirmed</u></b> when my sister poked it with a stick.",
            "We <b><u>squeezed</u></b> into the backseat of a small car yesterday.",
            "The old woman <b><u>begged</u></b> the rich man for some money.",
            '"I have not eaten my lunch," <b><u>replied</u></b> Sally.',
            "The dog <b><u>protected</u></b> its owner by barking fiercely at the robber.",
            "Mrs Lee <b><u>chose</u></b> the red box instead of the blue one.",
            "The shopping centre was <b><u>crowded</u></b> because there was a sale.",
            "He felt very <b><u>comfortable</u></b> sitting on that big sofa.",
            "Peter has a <b><u>fear</u></b> of sleeping alone.",
            "As the bed was <b><u>full</u></b>, there was little room for me to sleep."],
    },
    {
        "title": "Unit 3 - My Gumpy's Outing",
        "subtitle":"Unit 3",
        "testdate":"23/02/2023",
        "words": [
            "sheep",
            "stream",
            "creep",
            "pleaded",
            "bleated",
            "leaked",
            "teased",
            "trampled",
            "squabbled",
            "clasped",
            "falpped",
            "mucked",
            "owned",
            "field",
            "entrance"],
        "sentences": [
            "The farmer kept the <b><u>sheep</u></b> for its wool.",
            "As the <b><u>stream</u></b> was quite shallow, we were able to walk across it.",
            "I tried to <b><u>creep</u></b> around the corner, hoping my brother would not see me.",
            "Karen <b><u>pleaded</u></b> with her mother for a shopping trip.",
            "The goat <b><u>bleated</u></b> weakly in hunger.",
            "The water pipe had <b><u>leaked</u></b> so we called a plumber to fix it.",
            "Harry <b><u>teased</u></b> his cousin when he made a mistake.",
            "The horses <b><u>trampled</u></b> on the flowers as they galloped across the field.",
            "The boys <b><u>squabbled</u></b> noisily over a ball during recess.",
            "We <b><u>clasped</u></b> each other's hands so that none of us would be lost in the crowd.",
            "A yellow bird <b><u>flapped</u></b> its wings furiously and flew off.",
            "The children <b><u>mucked</u></b> about all afternoon and wasted a lot of time.",
            "My Gumpy <b><u>owned</u></b> a boat and his house was by a river.",
            "I saw a fox run across the <b><u>field</u></b>.",
            "When we arrived at the zoo, we saw that the <b><u>entrance</u></b> was packed with tourists."
        ]
    },
    {
        "title": "Unit 4 - A Day In the Kitchen with Grandma",
        "subtitle":"Unit 4",
        "testdate":"09/03/2023",
        "words": [
            "towel",
            "tooth",
            "noodles",
            "bamboo",
            "dough",
            "dumplings",
            "equipment",
            "refrigerator",
            "crushed",
            "stained",
            "shaped",
            "decorated",
            "stirred",
            "boiled",
            "fried"],
        "sentences": [
            "She used the kitchen <b><u>towel</u></b> to wipe the oily table.",
            "Grandma broke a <b><u>tooth</u></b> while she was eating some chilli crabs.",
            "I ordered chicken <b><u>noodles</u></b> for dinner.",
            "She wrapped the rice with <b><u>bamboo</u></b> leaves.",
            "Karen and her mother kneaded the <b><u>dough</u></b> to make bread.",
            "We eat rice <b><u>dumplings</u></b> during the Dragon Boat Festival.",
            "My parents went shopping for new kitchen <b><u>equipment</u></b> for our new house.",
            "Please keep the milk in the <b><u>refrigerator</u></b>.",
            "Grandma <b><u>crushed</u></b> the blue flowers to colour the rice.",
            "His shirt was <b><u>stained</u></b> with ink.",
            "The chef <b><u>shaped</u></b> with mixture into a ball.",
            "My siblings and I <b><u>decorated</u></b> the gingerbread cookied with icing.",
            "He <b><u>stirred</u></b> some milk into his coffee.",
            "Grandma <b><u>boiled</u></b> some eggs to add to the salad.",
            "My mother <b><u>fried</u></b> fish for yesterday's dinner."
        ]
    }
]