var mainData = [
    {
        "title": "Unit 1 - Chicken Rice",
        "subtitle":"Unit 1",
        "testdate":"26/01/2023",
        "words": [
            "dish",
            "lunch",
            "stall",
            "buzz",
            "hope",
            "snake",
            "crispy",
            "spicy",
            "delicious",
            "tasteless",
            "fresh",
            "disgusting",
            "ingredients",
            "curry puff",
            "chicken rice"],
        "sentences": [
            "My favourite <b><u>dish</u></b> is mee goreeng.",
            "I had nasi lemak for <b><u>lunch</u></b> yesterday afternoon.",
            "The <b><u>stall</u></b> that sells satay and ketupat is very crowded now.",
            "Sally was woken up by the <b><u>buzz</u></b> of a mosquito in her ear.",
            "We <b><u>hope</u></b> and pray that the operation will be a success.",
            "A <b><u>snake</u></b> slithered across our path.",
            "The fried chicken wings are <b><u>crispy</u></b> and tasty.",
            "The chilli is so <b><u>spicy</u></b> that I have to drink two big glasses water.",
            "The customers were very pleased with the <b><u>delicious</u></b> meal.",
            "The meat was dry and <b><u>tasteless</u></b>.",
            "Mother threw away the bread because it was not <b><u>fresh</u></b>.",
            "The food was so <b><u>disgusting</u></b> that none of us wanted to eat it.",
            "He created a fantastic meal from very few <b><u>ingredients</u></b>.",
            "I have eaten only one <b><u>curry puff</u></b> and I am already full.",
            "Mr Low tasted the <b><u>chicken rice</u></b> that he cooked and said that it was nice."],
    },
    {
        "title": "Unit 2 - Bad Dreams",
        "subtitle":"Unit 2",
        "testdate":"09/02/2023",
        "words": [
            "afraid",
            "sailed",
            "waited",
            "drain",
            "kitchen",
            "squirmed",
            "squeezed",
            "begged",
            "replied",
            "protected",
            "chose",
            "crowded",
            "confortable",
            "fear",
            "full"],
        "sentences": [
            "The boys were <b><u>afraid</u></b> of the dark.",
            "The boat <b><u>sailed</u></b> down the coast.",
            "I <b><u>waited</u></b> patiently for my turn to ride the horse.",
            "There was an unpleasant smell coming from the <b><u>drain</u></b>.",
            "Mother is busy cooking in the <b><u>kitchen</u></b>.",
            "The earthworm <b><u>squirmed</u></b> when my sister poked it with a stick.",
            "We <b><u>squeezed</u></b> into the backseat of a small car yesterday.",
            "The old woman <b><u>begged</u></b> the rich man for some money.",
            '"I have not eaten my lunch," <b><u>replied</u></b> Sally.',
            "The dog <b><u>protected</u></b> its owner by barking fiercely at the robber.",
            "Mrs Lee <b><u>chose</u></b> the red box instead of the blue one.",
            "The shopping centre was <b><u>crowded</u></b> because there was a sale.",
            "He felt very <b><u>comfortable</u></b> sitting on that big sofa.",
            "Peter has a <b><u>fear</u></b> of sleeping alone.",
            "As the bed was <b><u>full</u></b>, there was little room for me to sleep."],
    }
]