var mainData = [
  {
    title: "Unit 5 - Ruby's Sunflower",
    subtitle: "Unit 5",
    testdate: "Test Date 02/05/2025",
    words: [
      "contest",
      "measure",
      "judge",
      "crossly",
      "swimming",
      "lead",
      "special",
      "fetch",
      "slip",
      "practise",
      "straight",
      "snap",
      "scramble",
      "surprised",
      "whisper",
      "delight",
      "beat",
      "badge",
      "gardening",
      "stare"
    ],
    meanings: [],
    meanings_cn: [
      "比赛；竞赛",
      "测量；衡量",
      "评判；法官",
      "生气地；不耐烦地",
      "游泳",
      "带领；引导",
      "特别的；特殊的",
      "取来；拿来",
      "滑倒；滑动",
      "练习；实习",
      "笔直的",
      "猛地折断；啪的一声",
      "争抢；爬行；混乱",
      "惊讶的",
      "耳语",
      "高兴；欣喜",
      "打败；跳动",
      "徽章",
      "园艺",
      "凝视"
    ],
    pronunciation: [
      "/ˈkɒntest/",
      "/ˈmeʒər/",
      "/dʒʌdʒ/",
      "/ˈkrɒsli/",
      "/ˈswɪmɪŋ/",
      "/liːd/",
      "/ˈspɛʃl/",
      "/fetʃ/",
      "/slɪp/",
      "/ˈpræktɪs/",
      "/streɪt/",
      "/snæp/",
      "/ˈskræmbl/",
      "/sərˈpraɪzd/",
      "/ˈwɪspər/",
      "/dɪˈlaɪt/",
      "/biːt/",
      "/bædʒ/",
      "/ˈɡɑːrdnɪŋ/",
      "/ster/"
    ],
    sentences: []
  }
];
